{{- if .Values.redis.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "digiusher-k8s-agent.redis.fullname" . }}
  labels:
    {{- include "digiusher-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
  selector:
    {{- include "digiusher-k8s-agent.redis.selectorLabels" . | nindent 4 }}

{{- end }}