{{- if .Values.redis.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "digiusher-k8s-agent.redis.fullname" . }}
  labels:
    {{- include "digiusher-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.pvc.size }}
  {{- with .Values.redis.pvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}

{{- end }}