{{- if and .Values.agent.enabled .Values.agent.env.digiusher_k8s_api_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digiusher-k8s-agent.apiToken.secretName" . }}
  labels:
    {{- include "digiusher-k8s-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  K8S_API_TOKEN: {{ .Values.agent.env.digiusher_k8s_api_token | quote }}
{{- end }}
