apiVersion: v2
name: kube-cost-metrics-collector
version: 0.1.9
description: DigiUsher Kubernetes metrics collector.
type: application
dependencies:
  - name: prometheus
    version: "17.0.2"
    repository: https://prometheus-community.github.io/helm-charts
  - name: kube-service-selectors
    version: "1.0.7"
    repository: https://digiusher.github.io/helm-charts
maintainers:
  - name: digiusher
    email: support@digiusher.com
