{{- if and .Values.vmagent.enabled .Values.vmagent.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "digiusher-k8s-agent.vmagent.fullname" . }}
  labels:
    {{- include "digiusher-k8s-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: vmagent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vmagent.persistence.size }}
  {{- with .Values.vmagent.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
